### ISSUE TITLE
Geoalchemy assertion errors

### ISSUE THREAD

**Issue by hozn** [hozn/freezingsaddles#31]
Perhaps this is happening when we get null spatial points?

```
Traceback (most recent call last):
  File "/home/freezingsaddles/sites/freezingsaddles.com/freezingsaddles/bafs/scripts/sync_rides.py", line 117, in _write_rides
    ride = data.write_ride(strava_activity)
  File "/home/freezingsaddles/sites/freezingsaddles.com/freezingsaddles/bafs/data.py", line 293, in write_ride
    db.session.merge(ride_geo)
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1519, in merge
    load=load, _recursive=_recursive)
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1558, in _merge
    merged = self.query(mapper.class_).get(key[1])
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 820, in get
    return loading.load_on_ident(self, key)
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 226, in load_on_ident
    return q.one()
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2311, in one
    ret = list(self)
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 72, in instances
    rows = [process[0](row, None) for row in fetch]
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 72, in <listcomp>
    rows = [process[0](row, None) for row in fetch]
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 447, in _instance
    populate_state(state, dict_, row, isnew, only_load_props)
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 301, in populate_state
    populator(state, dict_, row)
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 151, in fetch_col
    dict_[key] = row[col]
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 89, in __getitem__
    return processor(self._row[index])
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/src/geoalchemy/geoalchemy/geometry.py", line 27, in process
    return DialectManager.get_spatial_dialect(dialect).process_result(value, self)
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/src/geoalchemy/geoalchemy/mysql.py", line 123, in process_result
    return MySQLPersistentSpatialElement(WKBSpatialElement(value, type.srid))
  File "/home/freezingsaddles/sites/freezingsaddles.com/env/src/geoalchemy/geoalchemy/base.py", line 90, in __init__
    assert isinstance(desc, str)
AssertionError
```

**Comment by hozn** [comment]
Fixed ... it was bytes.
